sudo: required

services:
  - docker

before_install:
  - docker build -t plasma018/docker-react -f Dockerfile.dev .

script:
  - docker run plasma018/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-402841806721"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $Access_key_ID
  secret_access_key: 
    secure: "$Secret_access_key" 


